import '../models/enums.dart';
import '../models/food.dart';

/// Built-in recipes so meal suggestions work offline and without AI credits.
/// Nutrition values are approximate per serving. Cost tier is a tag
/// (`cost:low|medium|high`) because absolute prices vary by country.
class RecipeLibrary {
  const RecipeLibrary._();

  static List<Recipe> all(String languageCode) => _data.map((d) => d.toRecipe(languageCode)).toList(growable: false);

  static Recipe? byId(String id, String languageCode) {
    for (final d in _data) {
      if (d.id == id) return d.toRecipe(languageCode);
    }
    return null;
  }
}

class _I {
  const _I(this.name, this.qty, [this.unit = '']);
  final String name;
  final double qty;
  final String unit;
}

class _R {
  const _R(
    this.id,
    this.en,
    this.tr,
    this.type,
    this.servings,
    this.nutrition,
    this.mins,
    this.diff,
    this.tags,
    this.items,
    this.stepsEn,
    this.stepsTr,
  );

  final String id;
  final String en;
  final String tr;
  final MealType type;
  final int servings;

  /// kcal, protein, carbs, fat per serving.
  final List<int> nutrition;
  final int mins;
  final Difficulty diff;
  final List<String> tags;
  final List<_I> items;
  final List<String> stepsEn, stepsTr;

  Recipe toRecipe(String lang) => Recipe(
    id: id,
    name: lang == 'tr' ? tr : en,
    mealType: type,
    ingredients: [for (final i in items) i.name],
    steps: lang == 'tr' ? stepsTr : stepsEn,
    calories: nutrition[0],
    proteinG: nutrition[1],
    carbsG: nutrition[2],
    fatG: nutrition[3],
    prepMinutes: mins,
    difficulty: diff,
    tags: tags,
    servings: servings,
    quantities: [for (final i in items) i.qty],
    units: [for (final i in items) i.unit],
  );
}

const _veg = 'vegetarian';
const _vegan = 'vegan';
const _gf = 'glutenFree';
const _pesc = 'pescatarian';
const _low = 'cost:low';
const _mid = 'cost:medium';
const _high = 'cost:high';
const _b = MealType.breakfast;
const _l = MealType.lunch;
const _d = MealType.dinner;
const _s = MealType.snack;
const _easy = Difficulty.easy;
const _med = Difficulty.medium;
const _hard = Difficulty.hard;

const _data = <_R>[
  // Breakfast ---------------------------------------------------------------
  _R(
    'oats_banana',
    'Banana Oatmeal',
    'Muzlu Yulaf Lapası',
    _b,
    1,
    [380, 12, 64, 8],
    10,
    _easy,
    [_veg, _low],
    [_I('oats', 50, 'g'), _I('milk', 250, 'ml'), _I('banana', 1), _I('honey', 1, 'tsp'), _I('cinnamon', 1, 'pinch')],
    [
      'Bring the milk to a simmer.',
      'Stir in the oats and cook for 5 minutes, stirring.',
      'Mash half the banana into the pot and slice the rest on top.',
      'Finish with honey and cinnamon.',
    ],
    [
      'Sütü kaynama noktasına getir.',
      'Yulafı ekle, karıştırarak 5 dakika pişir.',
      'Muzun yarısını ezip tencereye kat, kalanını dilimleyip üstüne koy.',
      'Bal ve tarçınla bitir.',
    ],
  ),
  _R(
    'menemen',
    'Menemen (Turkish Eggs)',
    'Menemen',
    _b,
    2,
    [320, 16, 14, 22],
    15,
    _easy,
    [_veg, _gf, _low],
    [_I('egg', 4), _I('tomato', 3), _I('pepper', 2), _I('onion', 1), _I('olive oil', 2, 'tbsp')],
    [
      'Chop the onion and peppers and soften them in olive oil for 4 minutes.',
      'Add grated tomatoes and cook until thick, about 5 minutes.',
      'Crack in the eggs, stir gently and take off the heat while still soft.',
      'Season with salt and chili flakes; serve with bread.',
    ],
    [
      'Soğanı ve biberleri doğra, zeytinyağında 4 dakika yumuşat.',
      'Rendelenmiş domatesleri ekle, suyunu çekene kadar 5 dakika pişir.',
      'Yumurtaları kır, hafifçe karıştır ve yumuşakken ocaktan al.',
      'Tuz ve pul biberle tatlandır, ekmekle servis et.',
    ],
  ),
  _R(
    'yogurt_bowl',
    'Greek Yogurt Bowl',
    'Yoğurt Kasesi',
    _b,
    1,
    [350, 18, 40, 12],
    5,
    _easy,
    [_veg, _gf, _low],
    [_I('yogurt', 200, 'g'), _I('banana', 1), _I('nuts', 30, 'g'), _I('honey', 1, 'tbsp')],
    ['Spoon the yogurt into a bowl.', 'Top with sliced banana and nuts.', 'Drizzle with honey.'],
    ['Yoğurdu kaseye al.', 'Üstüne dilimlenmiş muz ve kuruyemiş ekle.', 'Balı gezdir.'],
  ),
  _R(
    'avocado_toast',
    'Avocado Egg Toast',
    'Avokadolu Yumurtalı Tost',
    _b,
    1,
    [420, 17, 36, 24],
    10,
    _easy,
    [_veg, _mid],
    [_I('bread', 2, 'slice'), _I('avocado', 1), _I('egg', 1), _I('lemon', 0.5)],
    [
      'Toast the bread.',
      'Mash the avocado with lemon juice, salt and pepper.',
      'Fry or poach the egg.',
      'Spread the avocado on the toast and top with the egg.',
    ],
    [
      'Ekmeği kızart.',
      'Avokadoyu limon suyu, tuz ve karabiberle ez.',
      'Yumurtayı tavada ya da poşe pişir.',
      'Avokadoyu ekmeğe sür, yumurtayı üstüne koy.',
    ],
  ),
  _R(
    'cheese_omelette',
    'Cheese Omelette',
    'Peynirli Omlet',
    _b,
    1,
    [360, 22, 2, 29],
    8,
    _easy,
    [_veg, _gf, _low],
    [_I('egg', 3), _I('cheese', 40, 'g'), _I('butter', 1, 'tbsp')],
    [
      'Whisk the eggs with a pinch of salt.',
      'Melt the butter in a pan over medium heat.',
      'Pour in the eggs; when almost set, add the cheese.',
      'Fold in half and serve.',
    ],
    [
      'Yumurtaları bir tutam tuzla çırp.',
      'Tereyağını orta ateşte erit.',
      'Yumurtaları dök; neredeyse pişince peyniri ekle.',
      'İkiye katla ve servis et.',
    ],
  ),
  _R(
    'sucuklu_yumurta',
    'Eggs with Sucuk',
    'Sucuklu Yumurta',
    _b,
    2,
    [430, 24, 2, 36],
    10,
    _easy,
    [_gf, _mid],
    [_I('sucuk', 100, 'g'), _I('egg', 4), _I('butter', 1, 'tsp')],
    [
      'Slice the sucuk into thin rounds.',
      'Brown it in a pan with a little butter for 2 minutes.',
      'Crack the eggs over it, cover and cook until the whites set.',
    ],
    [
      'Sucuğu ince dilimle.',
      'Az tereyağıyla tavada 2 dakika kızart.',
      'Yumurtaları üstüne kır, kapağını kapat ve beyazı pişene kadar beklet.',
    ],
  ),
  _R(
    'pancakes',
    'Fluffy Pancakes',
    'Pankek',
    _b,
    2,
    [410, 13, 62, 12],
    20,
    _easy,
    [_veg, _low],
    [
      _I('flour', 150, 'g'),
      _I('milk', 200, 'ml'),
      _I('egg', 1),
      _I('sugar', 1, 'tbsp'),
      _I('butter', 1, 'tbsp'),
      _I('honey', 2, 'tbsp'),
    ],
    [
      'Whisk the flour, sugar and a pinch of salt.',
      'Add the milk, egg and melted butter; mix until just smooth.',
      'Cook ladlefuls in a lightly oiled pan until bubbles form, then flip.',
      'Serve with honey.',
    ],
    [
      'Un, şeker ve bir tutam tuzu karıştır.',
      'Süt, yumurta ve eritilmiş tereyağını ekleyip pürüzsüz olana kadar çırp.',
      'Hafif yağlı tavaya kepçeyle dök, kabarcıklar çıkınca çevir.',
      'Balla servis et.',
    ],
  ),
  _R(
    'peanut_toast',
    'Peanut Butter Banana Toast',
    'Fıstık Ezmeli Muzlu Tost',
    _b,
    1,
    [390, 13, 50, 16],
    5,
    _easy,
    [_vegan, _veg, _low],
    [_I('bread', 2, 'slice'), _I('peanut butter', 2, 'tbsp'), _I('banana', 1)],
    ['Toast the bread.', 'Spread the peanut butter.', 'Top with banana slices.'],
    ['Ekmeği kızart.', 'Fıstık ezmesini sür.', 'Üstüne muz dilimlerini diz.'],
  ),
  _R(
    'cilbir',
    'Turkish Poached Eggs (Çılbır)',
    'Çılbır',
    _b,
    2,
    [340, 19, 8, 26],
    15,
    _med,
    [_veg, _gf, _low],
    [_I('egg', 4), _I('yogurt', 200, 'g'), _I('garlic', 1, 'clove'), _I('butter', 2, 'tbsp')],
    [
      'Mix the yogurt with grated garlic and salt; spread it on plates.',
      'Poach the eggs in simmering water with a splash of vinegar for 3 minutes.',
      'Place the eggs on the yogurt.',
      'Melt the butter with chili flakes and pour it over.',
    ],
    [
      'Yoğurdu ezilmiş sarımsak ve tuzla karıştır, tabaklara yay.',
      'Yumurtaları sirkeli kaynar suda 3 dakika poşe et.',
      'Yumurtaları yoğurdun üstüne al.',
      'Tereyağını pul biberle eritip üzerine gezdir.',
    ],
  ),
  _R(
    'smoothie',
    'Strawberry Banana Smoothie',
    'Çilekli Muzlu Smoothie',
    _b,
    1,
    [280, 9, 52, 4],
    5,
    _easy,
    [_veg, _gf, _low],
    [_I('strawberry', 100, 'g'), _I('banana', 1), _I('milk', 200, 'ml'), _I('honey', 1, 'tsp')],
    ['Put everything into a blender.', 'Blend until smooth.', 'Pour and drink right away.'],
    ['Tüm malzemeleri blendera koy.', 'Pürüzsüz olana kadar çek.', 'Bardağa dök ve hemen iç.'],
  ),
  _R(
    'breakfast_plate',
    'Turkish Breakfast Plate',
    'Kahvaltı Tabağı',
    _b,
    1,
    [450, 20, 38, 24],
    10,
    _easy,
    [_veg, _mid],
    [_I('egg', 1), _I('cheese', 50, 'g'), _I('olives', 8), _I('tomato', 1), _I('cucumber', 1), _I('bread', 1, 'slice')],
    [
      'Boil the egg for 8 minutes.',
      'Slice the tomato and cucumber.',
      'Arrange everything on a plate with the cheese, olives and bread.',
    ],
    ['Yumurtayı 8 dakika haşla.', 'Domates ve salatalığı dilimle.', 'Peynir, zeytin ve ekmekle birlikte tabağa diz.'],
  ),
  _R(
    'overnight_oats',
    'Overnight Oats',
    'Gece Yulafı',
    _b,
    1,
    [360, 15, 52, 10],
    5,
    _easy,
    [_veg, _low],
    [
      _I('oats', 50, 'g'),
      _I('yogurt', 100, 'g'),
      _I('milk', 100, 'ml'),
      _I('strawberry', 50, 'g'),
      _I('honey', 1, 'tsp'),
    ],
    [
      'Mix the oats, yogurt and milk in a jar.',
      'Cover and leave in the fridge overnight.',
      'In the morning top with fruit and honey.',
    ],
    [
      'Yulaf, yoğurt ve sütü bir kavanozda karıştır.',
      'Kapağını kapat, bir gece buzdolabında beklet.',
      'Sabah meyve ve balla servis et.',
    ],
  ),
  _R(
    'cheese_toastie',
    'Cheese Toastie',
    'Kaşarlı Tost',
    _b,
    1,
    [380, 17, 36, 18],
    7,
    _easy,
    [_veg, _low],
    [_I('bread', 2, 'slice'), _I('cheese', 50, 'g'), _I('tomato', 0.5), _I('butter', 1, 'tsp')],
    [
      'Put the cheese and tomato slices between the bread.',
      'Butter the outside lightly.',
      'Toast in a pan or press until golden and melted.',
    ],
    [
      'Peyniri ve domates dilimlerini ekmeklerin arasına koy.',
      'Dışını hafifçe yağla.',
      'Tavada ya da tost makinesinde altın rengi olana kadar kızart.',
    ],
  ),

  // Lunch -------------------------------------------------------------------
  _R(
    'chicken_bowl',
    'Chicken Rice Bowl',
    'Tavuklu Pilav Kasesi',
    _l,
    2,
    [560, 40, 62, 14],
    25,
    _easy,
    [_gf, _mid],
    [_I('chicken', 300, 'g'), _I('rice', 150, 'g'), _I('tomato', 1), _I('cucumber', 1), _I('yogurt', 100, 'g')],
    [
      'Cook the rice.',
      'Season the chicken and cook it in a hot pan for 6–7 minutes per side, then slice.',
      'Dice the tomato and cucumber.',
      'Serve the rice with the chicken, vegetables and a spoon of yogurt.',
    ],
    [
      'Pirinci pişir.',
      'Tavuğu baharatla, kızgın tavada her yüzünü 6–7 dakika pişirip dilimle.',
      'Domates ve salatalığı küp doğra.',
      'Pilavın üstüne tavuk, sebze ve bir kaşık yoğurt koy.',
    ],
  ),
  _R(
    'lentil_soup',
    'Red Lentil Soup',
    'Mercimek Çorbası',
    _l,
    4,
    [290, 15, 42, 7],
    30,
    _easy,
    [_veg, _gf, _low],
    [_I('lentil', 200, 'g'), _I('onion', 1), _I('carrot', 1), _I('butter', 2, 'tbsp'), _I('lemon', 1)],
    [
      'Chop the onion and carrot and soften them in butter for 5 minutes.',
      'Add the rinsed lentils and 1.2 L of water.',
      'Simmer for 20 minutes until soft, then blend until smooth.',
      'Season and serve with lemon.',
    ],
    [
      'Soğan ve havucu doğra, tereyağında 5 dakika kavur.',
      'Yıkanmış mercimeği ve 1,2 litre suyu ekle.',
      '20 dakika yumuşayana kadar pişir, sonra blenderdan geçir.',
      'Tuzunu ayarla, limonla servis et.',
    ],
  ),
  _R(
    'ezogelin',
    'Ezogelin Soup',
    'Ezogelin Çorbası',
    _l,
    4,
    [260, 13, 42, 5],
    35,
    _easy,
    [_veg, _low],
    [
      _I('lentil', 150, 'g'),
      _I('bulgur', 50, 'g'),
      _I('rice', 30, 'g'),
      _I('onion', 1),
      _I('tomato paste', 1, 'tbsp'),
      _I('butter', 2, 'tbsp'),
      _I('mint', 1, 'tsp'),
    ],
    [
      'Soften the chopped onion in butter, then stir in the tomato paste.',
      'Add the lentils, bulgur, rice and 1.5 L of water.',
      'Simmer for 25 minutes until creamy.',
      'Stir in the dried mint and season.',
    ],
    [
      'Doğranmış soğanı tereyağında kavur, salçayı ekle.',
      'Mercimek, bulgur, pirinç ve 1,5 litre suyu ekle.',
      '25 dakika kıvam alana kadar pişir.',
      'Kuru naneyi ekle, tuzunu ayarla.',
    ],
  ),
  _R(
    'tomato_soup',
    'Tomato Soup',
    'Domates Çorbası',
    _l,
    4,
    [200, 6, 22, 10],
    25,
    _easy,
    [_veg, _low],
    [_I('tomato', 6), _I('flour', 2, 'tbsp'), _I('butter', 2, 'tbsp'), _I('milk', 200, 'ml'), _I('cheese', 40, 'g')],
    [
      'Melt the butter and stir in the flour for 1 minute.',
      'Add grated tomatoes and 800 ml of water; simmer for 15 minutes.',
      'Stir in the milk and blend.',
      'Serve with grated cheese.',
    ],
    [
      'Tereyağını erit, unu ekleyip 1 dakika kavur.',
      'Rendelenmiş domatesleri ve 800 ml suyu ekle, 15 dakika pişir.',
      'Sütü ekle ve blenderdan geçir.',
      'Rendelenmiş peynirle servis et.',
    ],
  ),
  _R(
    'chicken_soup',
    'Chicken Noodle Soup',
    'Tavuk Çorbası',
    _l,
    4,
    [240, 20, 22, 7],
    40,
    _easy,
    [_mid],
    [_I('chicken', 250, 'g'), _I('carrot', 1), _I('onion', 1), _I('pasta', 50, 'g'), _I('lemon', 1)],
    [
      'Boil the chicken in 1.5 L of water for 25 minutes; take it out and shred it.',
      'Add the diced carrot, onion and pasta to the broth and cook for 10 minutes.',
      'Return the chicken and season.',
      'Serve with lemon.',
    ],
    [
      'Tavuğu 1,5 litre suda 25 dakika haşla, çıkarıp didikle.',
      'Suyuna küp doğranmış havuç, soğan ve şehriyeyi ekleyip 10 dakika pişir.',
      'Tavuğu geri ekle, tuzunu ayarla.',
      'Limonla servis et.',
    ],
  ),
  _R(
    'tuna_salad',
    'Tuna Salad',
    'Ton Balıklı Salata',
    _l,
    2,
    [330, 26, 10, 20],
    10,
    _easy,
    [_pesc, _gf, _mid],
    [
      _I('tuna', 1, 'can'),
      _I('lettuce', 150, 'g'),
      _I('tomato', 2),
      _I('cucumber', 1),
      _I('olive oil', 2, 'tbsp'),
      _I('lemon', 0.5),
    ],
    [
      'Chop the lettuce, tomatoes and cucumber.',
      'Drain the tuna and add it on top.',
      'Dress with olive oil, lemon juice and salt.',
    ],
    [
      'Marul, domates ve salatalığı doğra.',
      'Ton balığının yağını süzüp üstüne ekle.',
      'Zeytinyağı, limon suyu ve tuzla tatlandır.',
    ],
  ),
  _R(
    'chickpea_salad',
    'Chickpea Salad',
    'Nohut Salatası',
    _l,
    2,
    [340, 13, 40, 14],
    10,
    _easy,
    [_vegan, _veg, _gf, _low],
    [
      _I('chickpeas', 1, 'can'),
      _I('tomato', 2),
      _I('cucumber', 1),
      _I('onion', 0.5),
      _I('parsley', 0.5, 'bunch'),
      _I('olive oil', 2, 'tbsp'),
      _I('lemon', 1),
    ],
    [
      'Drain and rinse the chickpeas.',
      'Dice the tomatoes, cucumber and onion; chop the parsley.',
      'Mix everything with olive oil, lemon juice and salt.',
    ],
    [
      'Nohutu süz ve yıka.',
      'Domates, salatalık ve soğanı küp doğra, maydanozu kıy.',
      'Hepsini zeytinyağı, limon suyu ve tuzla karıştır.',
    ],
  ),
  _R(
    'shepherds_salad',
    'Shepherd\'s Salad',
    'Çoban Salata',
    _l,
    2,
    [160, 3, 12, 12],
    10,
    _easy,
    [_vegan, _veg, _gf, _low],
    [
      _I('tomato', 3),
      _I('cucumber', 2),
      _I('pepper', 1),
      _I('onion', 1),
      _I('parsley', 0.5, 'bunch'),
      _I('olive oil', 2, 'tbsp'),
      _I('lemon', 1),
    ],
    [
      'Dice the tomatoes, cucumbers, pepper and onion small.',
      'Chop the parsley.',
      'Dress with olive oil, lemon juice and salt.',
    ],
    [
      'Domates, salatalık, biber ve soğanı küçük doğra.',
      'Maydanozu kıy.',
      'Zeytinyağı, limon suyu ve tuzla tatlandır.',
    ],
  ),
  _R(
    'potato_salad',
    'Turkish Potato Salad',
    'Patates Salatası',
    _l,
    3,
    [280, 5, 40, 11],
    25,
    _easy,
    [_vegan, _veg, _gf, _low],
    [_I('potato', 4), _I('onion', 1), _I('parsley', 0.5, 'bunch'), _I('olive oil', 3, 'tbsp'), _I('lemon', 1)],
    [
      'Boil the potatoes until tender, about 20 minutes; peel and cube them.',
      'Chop the onion and parsley.',
      'Mix with olive oil, lemon juice, salt and chili flakes.',
    ],
    [
      'Patatesleri yumuşayana kadar yaklaşık 20 dakika haşla, soyup küp doğra.',
      'Soğanı ve maydanozu kıy.',
      'Zeytinyağı, limon suyu, tuz ve pul biberle karıştır.',
    ],
  ),
  _R(
    'pasta_tomato',
    'Tomato Garlic Pasta',
    'Domatesli Makarna',
    _l,
    2,
    [520, 17, 82, 14],
    20,
    _easy,
    [_veg, _low],
    [
      _I('pasta', 200, 'g'),
      _I('tomato', 4),
      _I('garlic', 2, 'clove'),
      _I('olive oil', 2, 'tbsp'),
      _I('cheese', 30, 'g'),
    ],
    [
      'Boil the pasta in salted water.',
      'Fry the sliced garlic in olive oil for 1 minute.',
      'Add the chopped tomatoes and cook for 8 minutes into a sauce.',
      'Toss with the pasta and top with grated cheese.',
    ],
    [
      'Makarnayı tuzlu suda haşla.',
      'Dilimlenmiş sarımsağı zeytinyağında 1 dakika çevir.',
      'Doğranmış domatesleri ekle, 8 dakika sos kıvamına gelene kadar pişir.',
      'Makarnayla karıştır, üstüne rendelenmiş peynir serp.',
    ],
  ),
  _R(
    'bulgur_pilaf',
    'Bulgur Pilaf with Yogurt',
    'Bulgur Pilavı ve Yoğurt',
    _l,
    4,
    [380, 11, 62, 10],
    25,
    _easy,
    [_veg, _low],
    [
      _I('bulgur', 200, 'g'),
      _I('onion', 1),
      _I('tomato paste', 1, 'tbsp'),
      _I('butter', 2, 'tbsp'),
      _I('yogurt', 200, 'g'),
    ],
    [
      'Soften the chopped onion in butter.',
      'Stir in the tomato paste for 1 minute.',
      'Add the bulgur and 400 ml of hot water; cook covered on low for 15 minutes.',
      'Let it rest for 5 minutes and serve with yogurt.',
    ],
    [
      'Doğranmış soğanı tereyağında kavur.',
      'Salçayı ekle, 1 dakika çevir.',
      'Bulguru ve 400 ml sıcak suyu ekle, kapağı kapalı kısık ateşte 15 dakika pişir.',
      '5 dakika demlendir, yoğurtla servis et.',
    ],
  ),
  _R(
    'chicken_wrap',
    'Chicken Yogurt Wrap',
    'Tavuklu Dürüm',
    _l,
    2,
    [470, 34, 40, 18],
    15,
    _easy,
    [_mid],
    [_I('tortilla', 2), _I('chicken', 250, 'g'), _I('yogurt', 100, 'g'), _I('lettuce', 50, 'g'), _I('tomato', 1)],
    [
      'Cook the seasoned chicken strips for 8 minutes.',
      'Mix the yogurt with salt and a little garlic.',
      'Spread the sauce on the tortillas and add the lettuce, tomato and chicken.',
      'Roll up tightly and cut in half.',
    ],
    [
      'Baharatlı tavuğu şeritler halinde 8 dakika pişir.',
      'Yoğurdu tuz ve biraz sarımsakla karıştır.',
      'Sosu lavaşa sür; marul, domates ve tavuğu ekle.',
      'Sıkıca sar ve ortadan kes.',
    ],
  ),
  _R(
    'quesadilla',
    'Chicken Quesadilla',
    'Tavuklu Kesadilya',
    _l,
    2,
    [520, 36, 38, 24],
    15,
    _easy,
    [_mid],
    [_I('tortilla', 2), _I('chicken', 200, 'g'), _I('cheese', 80, 'g'), _I('pepper', 1), _I('onion', 0.5)],
    [
      'Cook the diced chicken with the pepper and onion for 8 minutes.',
      'Spread it over half of each tortilla and add the cheese.',
      'Fold and toast in a dry pan for 2 minutes per side.',
      'Cut into wedges.',
    ],
    [
      'Küp doğranmış tavuğu biber ve soğanla 8 dakika pişir.',
      'Lavaşların yarısına yay, peyniri ekle.',
      'Katla, yağsız tavada her yüzünü 2 dakika kızart.',
      'Üçgen dilimler halinde kes.',
    ],
  ),
  _R(
    'kuru_fasulye',
    'Turkish White Beans',
    'Kuru Fasulye',
    _l,
    4,
    [360, 18, 52, 8],
    40,
    _easy,
    [_vegan, _veg, _gf, _low],
    [_I('beans', 2, 'can'), _I('onion', 1), _I('pepper', 1), _I('tomato paste', 2, 'tbsp'), _I('olive oil', 2, 'tbsp')],
    [
      'Soften the onion and pepper in oil.',
      'Stir in the tomato paste.',
      'Add the drained beans and 500 ml of hot water.',
      'Simmer for 25 minutes; serve with rice or bread.',
    ],
    [
      'Soğanı ve biberi yağda kavur.',
      'Salçayı ekleyip çevir.',
      'Süzülmüş fasulyeyi ve 500 ml sıcak suyu ekle.',
      '25 dakika pişir; pilav ya da ekmekle servis et.',
    ],
  ),
  _R(
    'mercimek_kofte',
    'Lentil Patties',
    'Mercimek Köftesi',
    _l,
    4,
    [300, 13, 52, 6],
    40,
    _med,
    [_vegan, _veg, _low],
    [
      _I('lentil', 150, 'g'),
      _I('bulgur', 150, 'g'),
      _I('onion', 1),
      _I('tomato paste', 1, 'tbsp'),
      _I('parsley', 1, 'bunch'),
      _I('olive oil', 3, 'tbsp'),
      _I('lettuce', 100, 'g'),
      _I('lemon', 1),
    ],
    [
      'Boil the lentils in 600 ml of water until soft; stir in the bulgur, cover and rest for 15 minutes.',
      'Soften the onion in oil with the tomato paste.',
      'Knead everything with the chopped parsley, salt and spices.',
      'Shape into patties and serve on lettuce with lemon.',
    ],
    [
      'Mercimeği 600 ml suda yumuşayana kadar haşla, bulguru ekle, kapağı kapalı 15 dakika demlendir.',
      'Soğanı salçayla birlikte yağda kavur.',
      'Hepsini kıyılmış maydanoz, tuz ve baharatla yoğur.',
      'Köfte şekli ver, marul ve limonla servis et.',
    ],
  ),
  _R(
    'mucver',
    'Zucchini Fritters',
    'Mücver',
    _l,
    3,
    [260, 11, 20, 15],
    25,
    _med,
    [_veg, _low],
    [_I('zucchini', 3), _I('egg', 2), _I('flour', 4, 'tbsp'), _I('cheese', 60, 'g'), _I('dill', 0.5, 'bunch')],
    [
      'Grate the zucchini, salt it and squeeze out the water after 10 minutes.',
      'Mix with the eggs, flour, crumbled cheese and chopped dill.',
      'Fry spoonfuls in hot oil until golden on both sides.',
      'Serve with yogurt.',
    ],
    [
      'Kabakları rendele, tuzla ve 10 dakika sonra suyunu sık.',
      'Yumurta, un, ufalanmış peynir ve kıyılmış dereotuyla karıştır.',
      'Kızgın yağa kaşıkla dök, iki yüzü kızarana kadar pişir.',
      'Yoğurtla servis et.',
    ],
  ),
  _R(
    'hummus',
    'Hummus Plate',
    'Humus Tabağı',
    _l,
    3,
    [310, 11, 30, 17],
    10,
    _easy,
    [_vegan, _veg, _gf, _low],
    [
      _I('chickpeas', 1, 'can'),
      _I('tahini', 3, 'tbsp'),
      _I('lemon', 1),
      _I('garlic', 1, 'clove'),
      _I('olive oil', 2, 'tbsp'),
    ],
    [
      'Blend the drained chickpeas with the tahini, lemon juice, garlic and a little cold water.',
      'Season with salt and blend until creamy.',
      'Spread on a plate, drizzle with olive oil and serve with bread or vegetables.',
    ],
    [
      'Süzülmüş nohutu tahin, limon suyu, sarımsak ve biraz soğuk suyla blenderdan geçir.',
      'Tuzunu ayarla, krema kıvamına getir.',
      'Tabağa yay, zeytinyağı gezdir; ekmek ya da sebzeyle servis et.',
    ],
  ),

  // Dinner ------------------------------------------------------------------
  _R(
    'salmon_veg',
    'Baked Salmon & Vegetables',
    'Fırında Somon ve Sebze',
    _d,
    2,
    [540, 36, 32, 28],
    30,
    _med,
    [_pesc, _gf, _high],
    [_I('salmon', 2), _I('potato', 3), _I('broccoli', 200, 'g'), _I('olive oil', 2, 'tbsp'), _I('lemon', 1)],
    [
      'Heat the oven to 200 °C.',
      'Cube the potatoes, toss with oil and salt and roast for 10 minutes.',
      'Add the broccoli and salmon, season and squeeze lemon over.',
      'Roast for 15 more minutes.',
    ],
    [
      'Fırını 200 °C\'ye ısıt.',
      'Patatesleri küp doğra, yağ ve tuzla harmanla, 10 dakika pişir.',
      'Brokoli ve somonu ekle, baharatla, üstüne limon sık.',
      '15 dakika daha pişir.',
    ],
  ),
  _R(
    'chicken_stirfry',
    'Chicken Vegetable Stir-fry',
    'Sebzeli Tavuk Sote',
    _d,
    2,
    [520, 38, 56, 14],
    25,
    _med,
    [_mid],
    [
      _I('chicken', 300, 'g'),
      _I('pepper', 2),
      _I('onion', 1),
      _I('garlic', 2, 'clove'),
      _I('soy sauce', 3, 'tbsp'),
      _I('rice', 150, 'g'),
    ],
    [
      'Cook the rice.',
      'Stir-fry the chicken strips in a very hot pan for 5 minutes.',
      'Add the sliced pepper, onion and garlic; cook for 4 minutes.',
      'Add the soy sauce, toss and serve over the rice.',
    ],
    [
      'Pirinci pişir.',
      'Şerit doğranmış tavuğu çok kızgın tavada 5 dakika sotele.',
      'Dilimlenmiş biber, soğan ve sarımsağı ekle, 4 dakika pişir.',
      'Soya sosunu ekle, karıştır ve pilavla servis et.',
    ],
  ),
  _R(
    'tavuk_sote',
    'Chicken Sauté',
    'Tavuk Sote',
    _d,
    3,
    [380, 34, 14, 20],
    25,
    _easy,
    [_gf, _mid],
    [_I('chicken', 400, 'g'), _I('pepper', 2), _I('onion', 1), _I('mushroom', 150, 'g'), _I('tomato', 2)],
    [
      'Cook the cubed chicken in a hot pan until it releases and absorbs its juice.',
      'Add the onion and peppers; cook for 5 minutes.',
      'Add the mushrooms and diced tomatoes; cook for 8 minutes.',
      'Season and serve with rice or bulgur.',
    ],
    [
      'Kuşbaşı tavuğu kızgın tavada suyunu salıp çekene kadar pişir.',
      'Soğan ve biberleri ekle, 5 dakika pişir.',
      'Mantarı ve küp domatesleri ekle, 8 dakika pişir.',
      'Tuzunu ayarla, pilav ya da bulgurla servis et.',
    ],
  ),
  _R(
    'roast_chicken',
    'Roast Chicken & Potatoes',
    'Fırında Tavuk ve Patates',
    _d,
    4,
    [480, 36, 34, 20],
    50,
    _easy,
    [_gf, _mid],
    [
      _I('chicken', 600, 'g'),
      _I('potato', 5),
      _I('onion', 2),
      _I('garlic', 3, 'clove'),
      _I('lemon', 1),
      _I('olive oil', 3, 'tbsp'),
    ],
    [
      'Heat the oven to 200 °C.',
      'Toss the chicken, potato wedges and onion with oil, garlic, lemon and spices.',
      'Spread in a tray and roast for 40 minutes, turning once.',
      'Rest for 5 minutes before serving.',
    ],
    [
      'Fırını 200 °C\'ye ısıt.',
      'Tavuk, elma dilim patates ve soğanı yağ, sarımsak, limon ve baharatla harmanla.',
      'Tepsiye yay, bir kez çevirerek 40 dakika pişir.',
      'Servisten önce 5 dakika dinlendir.',
    ],
  ),
  _R(
    'kofte',
    'Köfte with Salad',
    'Köfte ve Salata',
    _d,
    3,
    [480, 30, 22, 30],
    30,
    _med,
    [_mid],
    [
      _I('mince', 400, 'g'),
      _I('onion', 1),
      _I('bread', 1, 'slice'),
      _I('egg', 1),
      _I('tomato', 2),
      _I('lettuce', 100, 'g'),
    ],
    [
      'Grate the onion; soak the bread and squeeze it out.',
      'Knead the mince, onion, bread, egg, salt and cumin for 3 minutes.',
      'Shape small patties and cook in a hot pan for 4 minutes per side.',
      'Serve with a tomato and lettuce salad.',
    ],
    [
      'Soğanı rendele, ekmeği ıslatıp sık.',
      'Kıyma, soğan, ekmek, yumurta, tuz ve kimyonu 3 dakika yoğur.',
      'Küçük köfteler yap, kızgın tavada her yüzünü 4 dakika pişir.',
      'Domates ve marul salatasıyla servis et.',
    ],
  ),
  _R(
    'bolognese',
    'Spaghetti Bolognese',
    'Kıymalı Makarna',
    _d,
    3,
    [620, 32, 78, 20],
    30,
    _easy,
    [_mid],
    [
      _I('pasta', 300, 'g'),
      _I('mince', 250, 'g'),
      _I('onion', 1),
      _I('garlic', 2, 'clove'),
      _I('tomato', 3),
      _I('tomato paste', 1, 'tbsp'),
    ],
    [
      'Boil the pasta.',
      'Brown the mince with the onion and garlic for 7 minutes.',
      'Add the tomato paste and chopped tomatoes; simmer for 12 minutes.',
      'Toss with the pasta.',
    ],
    [
      'Makarnayı haşla.',
      'Kıymayı soğan ve sarımsakla 7 dakika kavur.',
      'Salça ve doğranmış domatesleri ekle, 12 dakika pişir.',
      'Makarnayla karıştır.',
    ],
  ),
  _R(
    'karniyarik',
    'Stuffed Eggplant (Karnıyarık)',
    'Karnıyarık',
    _d,
    4,
    [420, 20, 20, 30],
    60,
    _hard,
    [_gf, _mid],
    [
      _I('eggplant', 4),
      _I('mince', 250, 'g'),
      _I('onion', 1),
      _I('pepper', 2),
      _I('tomato', 2),
      _I('tomato paste', 1, 'tbsp'),
    ],
    [
      'Peel the eggplants in stripes and fry or roast them until soft.',
      'Cook the mince with the onion, pepper, tomato and paste for 10 minutes.',
      'Slit the eggplants open and fill them with the mince.',
      'Bake at 190 °C with a little water for 25 minutes.',
    ],
    [
      'Patlıcanları alacalı soy, kızart ya da fırında yumuşat.',
      'Kıymayı soğan, biber, domates ve salçayla 10 dakika pişir.',
      'Patlıcanların ortasını yar, kıymayla doldur.',
      'Biraz suyla 190 °C fırında 25 dakika pişir.',
    ],
  ),
  _R(
    'etli_nohut',
    'Chickpeas with Beef',
    'Etli Nohut',
    _d,
    4,
    [450, 30, 42, 18],
    60,
    _med,
    [_gf, _mid],
    [
      _I('beef', 300, 'g'),
      _I('chickpeas', 2, 'can'),
      _I('onion', 1),
      _I('tomato paste', 2, 'tbsp'),
      _I('butter', 1, 'tbsp'),
    ],
    [
      'Brown the cubed beef in butter for 8 minutes.',
      'Add the onion and tomato paste; cook for 3 minutes.',
      'Add 600 ml of hot water, cover and simmer for 35 minutes.',
      'Add the chickpeas and cook for 15 more minutes.',
    ],
    [
      'Kuşbaşı eti tereyağında 8 dakika kavur.',
      'Soğanı ve salçayı ekle, 3 dakika pişir.',
      '600 ml sıcak su ekle, kapağı kapalı 35 dakika pişir.',
      'Nohutu ekle, 15 dakika daha pişir.',
    ],
  ),
  _R(
    'veg_curry',
    'Chickpea Vegetable Curry',
    'Nohutlu Sebze Köri',
    _d,
    3,
    [430, 15, 64, 12],
    30,
    _med,
    [_vegan, _veg, _gf, _low],
    [
      _I('chickpeas', 1, 'can'),
      _I('tomato', 3),
      _I('onion', 1),
      _I('garlic', 2, 'clove'),
      _I('spinach', 150, 'g'),
      _I('rice', 150, 'g'),
    ],
    [
      'Cook the rice.',
      'Soften the onion and garlic in oil with curry spices for 3 minutes.',
      'Add the chopped tomatoes and chickpeas; simmer for 12 minutes.',
      'Stir in the spinach until wilted and serve with the rice.',
    ],
    [
      'Pirinci pişir.',
      'Soğan ve sarımsağı köri baharatıyla yağda 3 dakika kavur.',
      'Doğranmış domatesleri ve nohutu ekle, 12 dakika pişir.',
      'Ispanağı ekleyip sönene kadar karıştır, pilavla servis et.',
    ],
  ),
  _R(
    'stuffed_pepper',
    'Rice-Stuffed Peppers',
    'Zeytinyağlı Biber Dolma',
    _d,
    4,
    [300, 6, 46, 11],
    50,
    _med,
    [_vegan, _veg, _gf, _low],
    [
      _I('pepper', 8),
      _I('rice', 150, 'g'),
      _I('onion', 2),
      _I('tomato', 1),
      _I('mint', 1, 'tsp'),
      _I('olive oil', 4, 'tbsp'),
    ],
    [
      'Soften the chopped onion in olive oil; add the rice, diced tomato, salt, mint and 150 ml of water and cook for 5 minutes.',
      'Fill the peppers three-quarters full.',
      'Stand them in a pot with 300 ml of water, cover and simmer for 35 minutes.',
      'Serve warm or cold.',
    ],
    [
      'Doğranmış soğanı zeytinyağında kavur; pirinç, küp domates, tuz, nane ve 150 ml suyu ekleyip 5 dakika pişir.',
      'Biberleri dörtte üçüne kadar doldur.',
      'Tencereye diz, 300 ml su ekle, kapağı kapalı 35 dakika pişir.',
      'Ilık ya da soğuk servis et.',
    ],
  ),
  _R(
    'taze_fasulye',
    'Green Beans in Olive Oil',
    'Zeytinyağlı Taze Fasulye',
    _d,
    4,
    [190, 5, 22, 10],
    45,
    _easy,
    [_vegan, _veg, _gf, _low],
    [_I('green beans', 500, 'g'), _I('onion', 1), _I('tomato', 2), _I('sugar', 1, 'tsp'), _I('olive oil', 4, 'tbsp')],
    [
      'Soften the sliced onion in olive oil.',
      'Add the trimmed beans, grated tomatoes, sugar, salt and 200 ml of water.',
      'Cover and simmer on low for 35 minutes.',
      'Serve at room temperature.',
    ],
    [
      'Piyazlık doğranmış soğanı zeytinyağında yumuşat.',
      'Ayıklanmış fasulye, rendelenmiş domates, şeker, tuz ve 200 ml suyu ekle.',
      'Kapağı kapalı kısık ateşte 35 dakika pişir.',
      'Oda sıcaklığında servis et.',
    ],
  ),
  _R(
    'ispanak',
    'Spinach with Rice',
    'Pirinçli Ispanak',
    _d,
    3,
    [220, 7, 28, 9],
    25,
    _easy,
    [_vegan, _veg, _gf, _low],
    [
      _I('spinach', 500, 'g'),
      _I('onion', 1),
      _I('rice', 50, 'g'),
      _I('tomato paste', 1, 'tbsp'),
      _I('olive oil', 3, 'tbsp'),
    ],
    [
      'Soften the onion in olive oil with the tomato paste.',
      'Add the washed, chopped spinach and let it wilt.',
      'Add the rice and 200 ml of hot water; cook covered for 15 minutes.',
      'Serve with yogurt.',
    ],
    [
      'Soğanı salçayla birlikte zeytinyağında kavur.',
      'Yıkanıp doğranmış ıspanağı ekle, sönmesini bekle.',
      'Pirinci ve 200 ml sıcak suyu ekle, kapağı kapalı 15 dakika pişir.',
      'Yoğurtla servis et.',
    ],
  ),
  _R(
    'patates_yemegi',
    'Potato Stew',
    'Patates Yemeği',
    _d,
    4,
    [260, 6, 40, 9],
    35,
    _easy,
    [_vegan, _veg, _gf, _low],
    [_I('potato', 5), _I('onion', 1), _I('pepper', 1), _I('tomato paste', 1, 'tbsp'), _I('olive oil', 3, 'tbsp')],
    [
      'Soften the onion and pepper in oil with the tomato paste.',
      'Add the cubed potatoes and enough hot water to just cover them.',
      'Simmer covered for 25 minutes until tender.',
    ],
    [
      'Soğan ve biberi salçayla birlikte yağda kavur.',
      'Küp doğranmış patatesi ve üstünü geçmeyecek kadar sıcak su ekle.',
      'Kapağı kapalı 25 dakika yumuşayana kadar pişir.',
    ],
  ),
  _R(
    'roast_veg',
    'Roasted Vegetables',
    'Fırın Sebze',
    _d,
    3,
    [240, 6, 30, 11],
    40,
    _easy,
    [_vegan, _veg, _gf, _low],
    [
      _I('zucchini', 2),
      _I('eggplant', 1),
      _I('pepper', 2),
      _I('potato', 2),
      _I('tomato', 2),
      _I('olive oil', 4, 'tbsp'),
    ],
    [
      'Heat the oven to 200 °C.',
      'Cut everything into chunks and toss with olive oil, salt and spices.',
      'Roast for 35 minutes, turning halfway.',
    ],
    [
      'Fırını 200 °C\'ye ısıt.',
      'Tüm sebzeleri iri doğra, zeytinyağı, tuz ve baharatla harmanla.',
      'Yarısında çevirerek 35 dakika pişir.',
    ],
  ),
  _R(
    'egg_fried_rice',
    'Egg Fried Rice',
    'Yumurtalı Pilav',
    _d,
    2,
    [450, 15, 68, 12],
    15,
    _easy,
    [_veg, _low],
    [
      _I('rice', 150, 'g'),
      _I('egg', 2),
      _I('peas', 80, 'g'),
      _I('pepper', 1),
      _I('onion', 1),
      _I('soy sauce', 2, 'tbsp'),
    ],
    [
      'Use cooked, cooled rice (or cook it first).',
      'Scramble the eggs in a hot pan and set them aside.',
      'Stir-fry the diced pepper, onion and peas for 3 minutes.',
      'Add the rice, eggs and soy sauce; toss until hot.',
    ],
    [
      'Pişmiş ve soğumuş pirinç kullan (yoksa önce pişir).',
      'Yumurtaları kızgın tavada karıştırarak pişir, kenara al.',
      'Küp doğranmış biber, soğan ve bezelyeyi 3 dakika sotele.',
      'Pilavı, yumurtayı ve soya sosunu ekle, ısınana kadar karıştır.',
    ],
  ),
  _R(
    'mushroom_risotto',
    'Mushroom Risotto',
    'Mantarlı Risotto',
    _d,
    2,
    [520, 15, 72, 18],
    40,
    _hard,
    [_veg, _gf, _mid],
    [_I('rice', 160, 'g'), _I('mushroom', 250, 'g'), _I('onion', 1), _I('butter', 2, 'tbsp'), _I('cheese', 40, 'g')],
    [
      'Brown the sliced mushrooms in half the butter and set them aside.',
      'Soften the onion in the rest of the butter, add the rice and stir for 1 minute.',
      'Add 800 ml of hot water or stock a ladle at a time, stirring, for about 18 minutes.',
      'Stir in the mushrooms and cheese and rest for 2 minutes.',
    ],
    [
      'Dilimlenmiş mantarları tereyağının yarısında kızart, kenara al.',
      'Soğanı kalan tereyağında yumuşat, pirinci ekleyip 1 dakika çevir.',
      '800 ml sıcak suyu ya da et suyunu kepçe kepçe ekleyerek yaklaşık 18 dakika karıştır.',
      'Mantarı ve peyniri ekle, 2 dakika dinlendir.',
    ],
  ),
  _R(
    'tuna_pasta',
    'Tuna Pasta',
    'Ton Balıklı Makarna',
    _d,
    2,
    [560, 32, 76, 14],
    15,
    _easy,
    [_pesc, _mid],
    [
      _I('pasta', 200, 'g'),
      _I('tuna', 1, 'can'),
      _I('corn', 80, 'g'),
      _I('parsley', 0.25, 'bunch'),
      _I('lemon', 0.5),
      _I('olive oil', 1, 'tbsp'),
    ],
    [
      'Boil the pasta.',
      'Mix the drained tuna and corn with olive oil, lemon juice and parsley.',
      'Toss with the warm pasta and season.',
    ],
    [
      'Makarnayı haşla.',
      'Süzülmüş ton balığı ve mısırı zeytinyağı, limon suyu ve maydanozla karıştır.',
      'Sıcak makarnayla harmanla, tuzunu ayarla.',
    ],
  ),
  _R(
    'fish_pan',
    'Pan-fried Fish',
    'Balık Tava',
    _d,
    2,
    [420, 34, 18, 24],
    20,
    _easy,
    [_pesc, _mid],
    [_I('fish', 400, 'g'), _I('flour', 4, 'tbsp'), _I('lemon', 1), _I('lettuce', 100, 'g'), _I('onion', 1)],
    [
      'Season the fish and dust it with flour.',
      'Fry in hot oil for 3–4 minutes per side.',
      'Serve with lemon, lettuce and sliced onion.',
    ],
    [
      'Balığı tuzla ve una bula.',
      'Kızgın yağda her yüzünü 3–4 dakika kızart.',
      'Limon, marul ve piyazlık soğanla servis et.',
    ],
  ),
  _R(
    'shrimp_guvec',
    'Garlic Shrimp Bake',
    'Karides Güveç',
    _d,
    2,
    [360, 30, 10, 22],
    20,
    _med,
    [_pesc, _gf, _high],
    [
      _I('shrimp', 300, 'g'),
      _I('garlic', 3, 'clove'),
      _I('pepper', 1),
      _I('tomato', 2),
      _I('butter', 2, 'tbsp'),
      _I('cheese', 50, 'g'),
    ],
    [
      'Heat the oven grill.',
      'Fry the garlic in butter, then add the diced pepper and tomato for 4 minutes.',
      'Add the shrimp and cook for 2 minutes.',
      'Top with cheese and grill until melted.',
    ],
    [
      'Fırının ızgarasını ısıt.',
      'Sarımsağı tereyağında çevir, küp biber ve domatesi ekleyip 4 dakika pişir.',
      'Karidesleri ekle, 2 dakika pişir.',
      'Üstüne peynir serp, eriyene kadar ızgarada tut.',
    ],
  ),

  // Snacks & desserts --------------------------------------------------------
  _R(
    'fruit_snack',
    'Fruit & Nuts',
    'Meyve ve Kuruyemiş',
    _s,
    1,
    [220, 5, 28, 11],
    2,
    _easy,
    [_vegan, _veg, _gf, _low],
    [_I('apple', 1), _I('nuts', 30, 'g')],
    ['Slice the apple.', 'Serve with a handful of nuts.'],
    ['Elmayı dilimle.', 'Bir avuç kuruyemişle servis et.'],
  ),
  _R(
    'cacik',
    'Cacık (Yogurt Cucumber Dip)',
    'Cacık',
    _s,
    3,
    [90, 5, 7, 4],
    5,
    _easy,
    [_veg, _gf, _low],
    [
      _I('yogurt', 300, 'g'),
      _I('cucumber', 1),
      _I('garlic', 1, 'clove'),
      _I('mint', 1, 'tsp'),
      _I('olive oil', 1, 'tbsp'),
    ],
    [
      'Grate or finely dice the cucumber.',
      'Mix with the yogurt, grated garlic, salt and 150 ml of cold water.',
      'Top with dried mint and olive oil.',
    ],
    [
      'Salatalığı rendele ya da ince doğra.',
      'Yoğurt, ezilmiş sarımsak, tuz ve 150 ml soğuk suyla karıştır.',
      'Üstüne kuru nane ve zeytinyağı gezdir.',
    ],
  ),
  _R(
    'ayran',
    'Ayran',
    'Ayran',
    _s,
    2,
    [70, 4, 5, 3],
    2,
    _easy,
    [_veg, _gf, _low],
    [_I('yogurt', 200, 'g')],
    ['Whisk the yogurt with 200 ml of cold water and a pinch of salt until frothy.', 'Serve chilled.'],
    ['Yoğurdu 200 ml soğuk su ve bir tutam tuzla köpürene kadar çırp.', 'Soğuk servis et.'],
  ),
  _R(
    'energy_balls',
    'Date Energy Balls',
    'Hurmalı Enerji Topları',
    _s,
    4,
    [180, 4, 26, 8],
    15,
    _easy,
    [_vegan, _veg, _gf, _low],
    [_I('dates', 150, 'g'), _I('nuts', 100, 'g'), _I('oats', 40, 'g')],
    [
      'Pit the dates.',
      'Blend the dates, nuts and oats into a sticky dough.',
      'Roll into small balls and chill for 20 minutes.',
    ],
    [
      'Hurmaların çekirdeğini çıkar.',
      'Hurma, kuruyemiş ve yulafı rondodan geçirip yapışkan bir hamur yap.',
      'Küçük toplar yuvarla, 20 dakika buzdolabında beklet.',
    ],
  ),
  _R(
    'baked_apple',
    'Baked Cinnamon Apples',
    'Tarçınlı Fırın Elma',
    _s,
    2,
    [160, 1, 32, 4],
    25,
    _easy,
    [_veg, _gf, _low],
    [_I('apple', 2), _I('nuts', 20, 'g'), _I('honey', 1, 'tbsp'), _I('cinnamon', 1, 'tsp')],
    [
      'Core the apples and stand them in a dish.',
      'Fill them with the nuts, cinnamon and honey.',
      'Bake at 180 °C for 20 minutes.',
    ],
    [
      'Elmaların çekirdek yuvasını oy, kaba diz.',
      'İçine kuruyemiş, tarçın ve bal koy.',
      '180 °C fırında 20 dakika pişir.',
    ],
  ),
  _R(
    'sutlac',
    'Rice Pudding (Sütlaç)',
    'Sütlaç',
    _s,
    4,
    [250, 7, 44, 5],
    40,
    _med,
    [_veg, _gf, _low],
    [_I('rice', 70, 'g'), _I('milk', 1000, 'ml'), _I('sugar', 120, 'g'), _I('cinnamon', 1, 'tsp')],
    [
      'Cook the rice in 300 ml of water until soft, about 10 minutes.',
      'Add the milk and simmer for 20 minutes, stirring often.',
      'Stir in the sugar and cook for 5 more minutes.',
      'Pour into bowls, chill and dust with cinnamon.',
    ],
    [
      'Pirinci 300 ml suda yaklaşık 10 dakika yumuşayana kadar haşla.',
      'Sütü ekle, sık sık karıştırarak 20 dakika pişir.',
      'Şekeri ekle, 5 dakika daha pişir.',
      'Kaselere paylaştır, soğut ve tarçın serp.',
    ],
  ),
];
