import '../models/enums.dart';
import '../models/food.dart';

/// Built-in recipes so meal suggestions work offline and without AI credits.
/// Nutrition values are approximate per serving. Cost tier is a tag
/// (`cost:low|medium|high`) because absolute prices vary by country.
class RecipeLibrary {
  const RecipeLibrary._();

  static List<Recipe> all(String languageCode) => _data.map((d) => d.toRecipe(languageCode)).toList(growable: false);
}

class _R {
  const _R(
    this.id,
    this.en,
    this.tr,
    this.type,
    this.ingredients,
    this.kcal,
    this.p,
    this.c,
    this.f,
    this.mins,
    this.diff,
    this.tags,
  );

  final String id;
  final String en;
  final String tr;
  final MealType type;
  final List<String> ingredients;
  final int kcal, p, c, f, mins;
  final Difficulty diff;
  final List<String> tags;

  Recipe toRecipe(String lang) => Recipe(
    id: id,
    name: lang == 'tr' ? tr : en,
    mealType: type,
    ingredients: ingredients,
    calories: kcal,
    proteinG: p,
    carbsG: c,
    fatG: f,
    prepMinutes: mins,
    difficulty: diff,
    tags: tags,
  );
}

const _veg = 'vegetarian';
const _vegan = 'vegan';
const _gf = 'glutenFree';
const _pesc = 'pescatarian';

const _data = <_R>[
  _R(
    'oats_banana',
    'Banana Oatmeal',
    'Muzlu Yulaf Lapası',
    MealType.breakfast,
    ['oats', 'milk', 'banana', 'honey'],
    380,
    12,
    64,
    8,
    10,
    Difficulty.easy,
    [_veg, 'cost:low'],
  ),
  _R(
    'menemen',
    'Menemen (Turkish Eggs)',
    'Menemen',
    MealType.breakfast,
    ['egg', 'tomato', 'pepper', 'onion', 'olive oil'],
    320,
    16,
    14,
    22,
    15,
    Difficulty.easy,
    [_veg, _gf, 'cost:low'],
  ),
  _R(
    'yogurt_bowl',
    'Greek Yogurt Bowl',
    'Yoğurt Kasesi',
    MealType.breakfast,
    ['yogurt', 'honey', 'nuts', 'banana'],
    350,
    18,
    42,
    12,
    5,
    Difficulty.easy,
    [_veg, _gf, 'cost:low'],
  ),
  _R(
    'avocado_toast',
    'Avocado Egg Toast',
    'Avokadolu Yumurtalı Tost',
    MealType.breakfast,
    ['bread', 'avocado', 'egg', 'lemon'],
    420,
    17,
    34,
    24,
    10,
    Difficulty.easy,
    [_veg, 'cost:medium'],
  ),
  _R(
    'cheese_omelette',
    'Cheese Omelette',
    'Peynirli Omlet',
    MealType.breakfast,
    ['egg', 'cheese', 'butter'],
    360,
    24,
    2,
    28,
    10,
    Difficulty.easy,
    [_veg, _gf, 'cost:low'],
  ),
  _R(
    'chicken_bowl',
    'Chicken Rice Bowl',
    'Tavuklu Pilav Kasesi',
    MealType.lunch,
    ['chicken', 'rice', 'tomato', 'cucumber', 'yogurt'],
    560,
    42,
    62,
    14,
    30,
    Difficulty.easy,
    [_gf, 'cost:medium'],
  ),
  _R(
    'lentil_soup',
    'Red Lentil Soup',
    'Mercimek Çorbası',
    MealType.lunch,
    ['lentil', 'onion', 'carrot', 'butter', 'lemon'],
    310,
    16,
    46,
    7,
    35,
    Difficulty.easy,
    [_veg, _gf, 'cost:low'],
  ),
  _R(
    'tuna_salad',
    'Tuna Salad',
    'Ton Balıklı Salata',
    MealType.lunch,
    ['tuna', 'lettuce', 'tomato', 'cucumber', 'olive oil', 'lemon'],
    380,
    30,
    10,
    24,
    10,
    Difficulty.easy,
    [_pesc, _gf, 'cost:medium'],
  ),
  _R(
    'chickpea_salad',
    'Chickpea Salad',
    'Nohut Salatası',
    MealType.lunch,
    ['chickpeas', 'tomato', 'cucumber', 'onion', 'olive oil', 'lemon'],
    420,
    15,
    48,
    18,
    10,
    Difficulty.easy,
    [_vegan, _veg, _gf, 'cost:low'],
  ),
  _R(
    'pasta_tomato',
    'Tomato Basil Pasta',
    'Domatesli Makarna',
    MealType.lunch,
    ['pasta', 'tomato', 'garlic', 'olive oil', 'cheese'],
    540,
    18,
    82,
    16,
    20,
    Difficulty.easy,
    [_veg, 'cost:low'],
  ),
  _R(
    'bulgur_pilaf',
    'Bulgur Pilaf with Yogurt',
    'Bulgur Pilavı ve Yoğurt',
    MealType.lunch,
    ['bulgur', 'tomato paste', 'onion', 'butter', 'yogurt'],
    450,
    14,
    72,
    12,
    25,
    Difficulty.easy,
    [_veg, 'cost:low'],
  ),
  _R(
    'salmon_veg',
    'Baked Salmon & Vegetables',
    'Fırında Somon ve Sebze',
    MealType.dinner,
    ['salmon', 'potato', 'broccoli', 'olive oil', 'lemon'],
    610,
    40,
    38,
    32,
    35,
    Difficulty.medium,
    [_pesc, _gf, 'cost:high'],
  ),
  _R(
    'chicken_stirfry',
    'Chicken Vegetable Stir-fry',
    'Sebzeli Tavuk Sote',
    MealType.dinner,
    ['chicken', 'pepper', 'onion', 'rice', 'soy sauce', 'garlic'],
    590,
    44,
    60,
    16,
    25,
    Difficulty.medium,
    ['cost:medium'],
  ),
  _R(
    'kofte',
    'Köfte with Salad',
    'Köfte ve Salata',
    MealType.dinner,
    ['mince', 'onion', 'bread', 'egg', 'tomato', 'lettuce'],
    650,
    38,
    28,
    42,
    35,
    Difficulty.medium,
    ['cost:medium'],
  ),
  _R(
    'veg_curry',
    'Chickpea Vegetable Curry',
    'Nohutlu Sebze Köri',
    MealType.dinner,
    ['chickpeas', 'tomato', 'onion', 'spinach', 'rice', 'garlic'],
    520,
    17,
    86,
    12,
    30,
    Difficulty.medium,
    [_vegan, _veg, _gf, 'cost:low'],
  ),
  _R(
    'stuffed_pepper',
    'Rice-Stuffed Peppers',
    'Zeytinyağlı Biber Dolma',
    MealType.dinner,
    ['pepper', 'rice', 'onion', 'tomato', 'olive oil'],
    430,
    8,
    70,
    14,
    50,
    Difficulty.medium,
    [_vegan, _veg, _gf, 'cost:low'],
  ),
  _R(
    'egg_fried_rice',
    'Egg Fried Rice',
    'Yumurtalı Pilav',
    MealType.dinner,
    ['rice', 'egg', 'pepper', 'onion', 'soy sauce'],
    520,
    18,
    72,
    16,
    15,
    Difficulty.easy,
    [_veg, 'cost:low'],
  ),
  _R(
    'mushroom_risotto',
    'Mushroom Risotto',
    'Mantarlı Risotto',
    MealType.dinner,
    ['rice', 'mushroom', 'onion', 'butter', 'cheese'],
    580,
    16,
    78,
    20,
    40,
    Difficulty.hard,
    [_veg, _gf, 'cost:medium'],
  ),
  _R(
    'chicken_wrap',
    'Chicken Yogurt Wrap',
    'Yoğurtlu Tavuk Dürüm',
    MealType.lunch,
    ['chicken', 'tortilla', 'yogurt', 'lettuce', 'tomato'],
    520,
    40,
    44,
    18,
    15,
    Difficulty.easy,
    ['cost:medium'],
  ),
  _R(
    'fruit_snack',
    'Fruit & Nuts',
    'Meyve ve Kuruyemiş',
    MealType.snack,
    ['apple', 'nuts'],
    230,
    6,
    26,
    12,
    2,
    Difficulty.easy,
    [_vegan, _veg, _gf, 'cost:low'],
  ),
];
