import '../models/enums.dart';

/// Keyword-based shopping categorizer (en + tr). AI categorization is only
/// used as a fallback for unknown items.
class ShoppingCategorizer {
  const ShoppingCategorizer();

  static const Map<ShoppingCategory, List<String>> _words = {
    ShoppingCategory.produce: [
      'apple',
      'banana',
      'tomato',
      'potato',
      'onion',
      'garlic',
      'lettuce',
      'spinach',
      'carrot',
      'pepper',
      'cucumber',
      'lemon',
      'orange',
      'fruit',
      'vegetable',
      'avocado',
      'broccoli',
      'mushroom',
      'herb',
      'elma',
      'muz',
      'domates',
      'patates',
      'soğan',
      'sogan',
      'sarımsak',
      'marul',
      'ıspanak',
      'havuç',
      'biber',
      'salatalık',
      'limon',
      'portakal',
      'meyve',
      'sebze',
      'mantar',
      'maydanoz',
    ],
    ShoppingCategory.meat: [
      'chicken',
      'beef',
      'pork',
      'lamb',
      'turkey',
      'fish',
      'salmon',
      'tuna',
      'mince',
      'sausage',
      'meat',
      'tavuk',
      'dana',
      'kuzu',
      'hindi',
      'balık',
      'balik',
      'somon',
      'kıyma',
      'kiyma',
      'sucuk',
      'et',
    ],
    ShoppingCategory.dairy: [
      'milk',
      'cheese',
      'yogurt',
      'yoghurt',
      'butter',
      'cream',
      'egg',
      'eggs',
      'süt',
      'sut',
      'peynir',
      'yoğurt',
      'yogurt',
      'tereyağ',
      'krema',
      'yumurta',
      'ayran',
    ],
    ShoppingCategory.bakery: ['bread', 'bagel', 'croissant', 'tortilla', 'ekmek', 'simit', 'lavaş', 'poğaça'],
    ShoppingCategory.pantry: [
      'rice',
      'pasta',
      'flour',
      'sugar',
      'salt',
      'oil',
      'olive oil',
      'beans',
      'lentil',
      'oats',
      'cereal',
      'spice',
      'sauce',
      'honey',
      'coffee',
      'tea',
      'nuts',
      'pirinç',
      'pirinc',
      'makarna',
      'un',
      'şeker',
      'seker',
      'tuz',
      'yağ',
      'zeytinyağı',
      'fasulye',
      'mercimek',
      'yulaf',
      'baharat',
      'salça',
      'bal',
      'kahve',
      'çay',
      'bulgur',
      'nohut',
    ],
    ShoppingCategory.frozen: ['frozen', 'ice cream', 'dondurulmuş', 'dondurma'],
    ShoppingCategory.drinks: ['water', 'juice', 'soda', 'cola', 'beer', 'wine', 'su', 'meyve suyu', 'kola', 'gazoz'],
    ShoppingCategory.household: [
      'detergent',
      'soap',
      'paper towel',
      'toilet paper',
      'trash bag',
      'sponge',
      'cleaner',
      'bleach',
      'deterjan',
      'sabun',
      'kağıt havlu',
      'tuvalet kağıdı',
      'çöp torbası',
      'sünger',
      'çamaşır suyu',
    ],
    ShoppingCategory.personalCare: [
      'shampoo',
      'toothpaste',
      'toothbrush',
      'deodorant',
      'razor',
      'lotion',
      'şampuan',
      'diş macunu',
      'diş fırçası',
      'deodorant',
      'jilet',
    ],
  };

  /// Returns null when unknown so callers can fall back to AI or "other".
  ShoppingCategory? categorize(String name) {
    final n = ' ${name.toLowerCase().trim()} ';
    ShoppingCategory? best;
    var bestLen = 0;
    _words.forEach((cat, words) {
      for (final w in words) {
        // Short words (≤3 chars, e.g. "et", "su", "un") must match whole words.
        final hit = w.length <= 3 ? RegExp('[\\s,]${RegExp.escape(w)}[\\s,]').hasMatch(n) : n.contains(w);
        if (hit && w.length > bestLen) {
          best = cat;
          bestLen = w.length;
        }
      }
    });
    return best;
  }
}
