"""Seed vocabulary for the on-device classifiers (English + Turkish).

This is *synthetic* training data: realistic short phrases built from these
terms, merchant names and templates. It gives the models sensible behaviour on
day one; retrain with real (anonymised, user-confirmed) corrections later.
"""

EXPENSE = {
    "food": {
        "en": ["lunch", "dinner", "breakfast", "coffee", "latte", "cappuccino", "espresso", "tea", "restaurant",
               "cafe", "groceries", "grocery store", "supermarket", "market", "bakery", "bread", "pizza", "burger",
               "sushi", "kebab", "sandwich", "takeaway", "food delivery", "snack", "lunch with team", "dinner out",
               "brunch", "dessert", "ice cream", "fruit", "vegetables", "meat", "chicken", "milk", "eggs", "water bottle",
               "starbucks", "mcdonalds", "burger king", "kfc", "dominos", "subway", "uber eats", "deliveroo",
               "walmart groceries", "tesco", "lidl", "aldi", "carrefour", "whole foods", "doughnut", "bagel", "smoothie",
               "juice", "beer at dinner", "wine for dinner", "food court", "street food", "noodles", "salad"],
        "tr": ["öğle yemeği", "öğlen yemeği", "akşam yemeği", "kahvaltı", "kahve", "çay", "restoran", "lokanta",
               "kafe", "market", "süpermarket", "bakkal", "manav", "fırın", "ekmek", "simit", "poğaça", "pizza",
               "hamburger", "döner", "dürüm", "lahmacun", "pide", "köfte", "kebap", "tost", "sandviç", "paket servis",
               "yemek siparişi", "atıştırmalık", "tatlı", "dondurma", "meyve", "sebze", "et", "tavuk", "süt", "yumurta",
               "su", "migros", "bim", "a101", "şok market", "carrefoursa", "getir", "yemeksepeti", "trendyol yemek",
               "kasap", "pastane", "baklava", "börek", "çorba", "mantı", "ev alışverişi yiyecek", "sucuk", "peynir"],
    },
    "transport": {
        "en": ["taxi", "uber", "lyft", "bolt", "bus", "bus ticket", "metro", "subway ticket", "train", "train ticket",
               "tram", "ferry", "fuel", "gas", "petrol", "diesel", "gas station", "shell", "bp", "parking", "parking fee",
               "toll", "bridge toll", "car wash", "car repair", "oil change", "tires", "flight", "plane ticket",
               "airport shuttle", "scooter rental", "bike rental", "transit card", "metro card top up", "car rental",
               "mechanic", "highway toll", "commute"],
        "tr": ["taksi", "bitaksi", "otobüs", "otobüs bileti", "metro", "metrobüs", "tramvay", "vapur", "marmaray",
               "dolmuş", "minibüs", "tren", "tren bileti", "yht", "benzin", "mazot", "motorin", "akaryakıt", "yakıt",
               "lpg", "opet", "petrol ofisi", "shell benzin", "otopark", "otopark ücreti", "köprü geçişi", "otoyol",
               "hgs", "ogs", "araba yıkama", "oto tamir", "lastik", "uçak bileti", "havalimanı servisi", "scooter",
               "martı", "istanbulkart", "kart dolumu", "araç kiralama", "sanayi", "servis ücreti"],
    },
    "shopping": {
        "en": ["clothes", "shirt", "t-shirt", "jeans", "dress", "shoes", "sneakers", "jacket", "coat", "bag",
               "backpack", "amazon order", "online order", "electronics", "headphones", "phone case", "charger",
               "laptop", "gift", "birthday gift", "present", "cosmetics", "makeup", "perfume", "jewelry", "watch",
               "furniture", "ikea", "home decor", "books", "stationery", "toys", "zara", "h&m", "uniqlo", "nike",
               "adidas", "mall", "shopping", "sunglasses", "household items", "kitchenware", "cleaning supplies"],
        "tr": ["kıyafet", "gömlek", "tişört", "pantolon", "kot", "elbise", "ayakkabı", "spor ayakkabı", "mont",
               "ceket", "çanta", "sırt çantası", "trendyol", "hepsiburada", "amazon siparişi", "n11", "internet alışverişi",
               "elektronik", "kulaklık", "telefon kılıfı", "şarj aleti", "bilgisayar", "hediye", "doğum günü hediyesi",
               "kozmetik", "makyaj", "parfüm", "takı", "saat", "mobilya", "ikea", "ev dekorasyonu", "kitap", "kırtasiye",
               "oyuncak", "lc waikiki", "defacto", "koton", "mavi", "zara", "avm", "alışveriş", "gözlük", "temizlik malzemesi",
               "mutfak eşyası", "deterjan"],
    },
    "bills": {
        "en": ["electricity bill", "electric bill", "power bill", "water bill", "gas bill", "heating", "internet bill",
               "wifi", "phone bill", "mobile bill", "utility bill", "utilities", "broadband", "cable tv bill",
               "building fee", "hoa fee", "property tax", "trash collection", "sewer bill", "energy bill"],
        "tr": ["elektrik faturası", "elektrik", "su faturası", "doğalgaz", "doğalgaz faturası", "kombi", "ısınma",
               "internet faturası", "internet", "telefon faturası", "cep telefonu faturası", "fatura", "turkcell",
               "vodafone", "türk telekom", "superonline", "aidat", "site aidatı", "apartman aidatı", "emlak vergisi",
               "çöp vergisi", "enerjisa", "igdaş", "iski", "başkentgaz"],
    },
    "housing": {
        "en": ["rent", "monthly rent", "mortgage", "mortgage payment", "landlord", "apartment rent", "deposit",
               "home insurance", "house repair", "plumber", "electrician", "moving costs", "storage unit"],
        "tr": ["kira", "ev kirası", "aylık kira", "konut kredisi", "ev kredisi", "ev sahibi", "depozito", "dask",
               "konut sigortası", "tadilat", "tesisatçı", "elektrikçi", "nakliyat", "taşınma", "boya badana"],
    },
    "entertainment": {
        "en": ["movie", "cinema", "movie tickets", "concert", "concert ticket", "theatre", "show", "museum",
               "bowling", "games", "video game", "steam", "playstation", "xbox", "bar", "drinks with friends", "party",
               "club", "festival", "escape room", "karaoke", "amusement park", "zoo", "football match", "match ticket",
               "pub", "night out", "billiards"],
        "tr": ["sinema", "film", "sinema bileti", "konser", "konser bileti", "tiyatro", "gösteri", "müze", "bowling",
               "oyun", "video oyunu", "steam oyun", "playstation", "bar", "arkadaşlarla içki", "parti", "kulüp",
               "festival", "kaçış odası", "karaoke", "lunapark", "hayvanat bahçesi", "maç", "maç bileti", "bilet",
               "eğlence", "gece dışarı", "bilardo", "nargile"],
    },
    "health": {
        "en": ["pharmacy", "medicine", "drugstore", "doctor", "doctor visit", "dentist", "hospital", "clinic",
               "vitamins", "gym", "gym membership", "yoga class", "pilates", "therapy session", "physio", "glasses",
               "contact lenses", "health insurance", "blood test", "prescription", "massage", "personal trainer"],
        "tr": ["eczane", "ilaç", "doktor", "muayene", "diş hekimi", "dişçi", "hastane", "klinik", "vitamin",
               "spor salonu", "gym üyeliği", "yoga dersi", "pilates", "terapi", "fizik tedavi", "gözlükçü", "lens",
               "sağlık sigortası", "tahlil", "kan tahlili", "reçete", "masaj", "kişisel antrenör", "muayene ücreti"],
    },
    "subscriptions": {
        "en": ["netflix", "spotify", "youtube premium", "disney plus", "hbo max", "apple music", "icloud",
               "google one", "amazon prime", "prime video", "chatgpt plus", "subscription", "monthly subscription",
               "app subscription", "newspaper subscription", "patreon", "dropbox", "adobe", "microsoft 365", "xbox game pass"],
        "tr": ["netflix", "spotify", "youtube premium", "disney plus", "blutv", "exxen", "gain", "tod", "beın connect",
               "icloud", "google one", "amazon prime", "abonelik", "aylık abonelik", "uygulama aboneliği", "üyelik",
               "dergi aboneliği", "storytel", "office 365", "game pass"],
    },
    "other": {
        "en": ["miscellaneous", "fee", "bank fee", "atm fee", "donation", "charity", "haircut", "barber", "laundry",
               "dry cleaning", "pet food", "vet", "post office", "shipping", "printing", "tips", "fine", "visa fee",
               "lottery", "cash withdrawal", "transfer fee", "babysitter"],
        "tr": ["diğer", "çeşitli", "masraf", "banka masrafı", "atm ücreti", "bağış", "berber", "kuaför", "çamaşırhane",
               "kuru temizleme", "kedi maması", "köpek maması", "veteriner", "kargo", "ptt", "fotokopi", "bahşiş",
               "ceza", "vize ücreti", "piyango", "nakit çekim", "eft ücreti", "bakıcı", "noter"],
    },
}

SHOPPING = {
    "produce": {
        "en": ["apples", "apple", "bananas", "banana", "tomatoes", "tomato", "potatoes", "onions", "garlic", "lettuce",
               "spinach", "carrots", "peppers", "cucumber", "lemons", "oranges", "grapes", "strawberries", "avocado",
               "broccoli", "mushrooms", "parsley", "zucchini", "eggplant", "cabbage", "watermelon", "pears", "herbs"],
        "tr": ["elma", "muz", "domates", "patates", "soğan", "sarımsak", "marul", "ıspanak", "havuç", "biber",
               "salatalık", "limon", "portakal", "üzüm", "çilek", "avokado", "brokoli", "mantar", "maydanoz", "kabak",
               "patlıcan", "lahana", "karpuz", "armut", "dereotu", "nane", "roka", "mandalina", "kiraz"],
    },
    "meat": {
        "en": ["chicken", "chicken breast", "beef", "ground beef", "steak", "pork", "lamb", "turkey", "fish",
               "salmon", "tuna", "shrimp", "sausage", "bacon", "ham", "meatballs", "chicken wings"],
        "tr": ["tavuk", "tavuk göğsü", "dana eti", "kıyma", "biftek", "kuzu eti", "hindi", "balık", "somon",
               "ton balığı", "karides", "sucuk", "salam", "sosis", "pastırma", "köftelik", "tavuk kanat", "levrek", "hamsi"],
    },
    "dairy": {
        "en": ["milk", "cheese", "yogurt", "butter", "cream", "eggs", "egg", "sour cream", "cream cheese",
               "mozzarella", "cheddar", "kefir", "whipping cream"],
        "tr": ["süt", "peynir", "beyaz peynir", "kaşar", "yoğurt", "tereyağı", "krema", "yumurta", "ayran", "kefir",
               "labne", "lor", "kaymak", "süzme yoğurt", "çökelek"],
    },
    "bakery": {
        "en": ["bread", "baguette", "bagels", "croissants", "tortillas", "buns", "pita", "muffins", "rolls"],
        "tr": ["ekmek", "tam buğday ekmeği", "simit", "poğaça", "lavaş", "pide", "açma", "kruvasan", "bazlama", "yufka"],
    },
    "pantry": {
        "en": ["rice", "pasta", "spaghetti", "flour", "sugar", "salt", "olive oil", "oil", "beans", "lentils",
               "oats", "cereal", "honey", "jam", "peanut butter", "coffee beans", "tea bags", "spices", "tomato sauce",
               "canned tuna", "chickpeas", "nuts", "vinegar", "soy sauce", "crackers", "chocolate", "biscuits"],
        "tr": ["pirinç", "makarna", "spagetti", "un", "şeker", "tuz", "zeytinyağı", "ayçiçek yağı", "fasulye",
               "mercimek", "yulaf", "mısır gevreği", "bal", "reçel", "fıstık ezmesi", "kahve", "çay", "baharat",
               "salça", "konserve", "nohut", "bulgur", "kuruyemiş", "sirke", "zeytin", "çikolata", "bisküvi", "kraker"],
    },
    "frozen": {
        "en": ["frozen pizza", "frozen vegetables", "ice cream", "frozen fries", "frozen peas", "frozen berries"],
        "tr": ["dondurulmuş pizza", "dondurulmuş sebze", "dondurma", "donuk patates", "dondurulmuş bezelye",
               "dondurulmuş mantı"],
    },
    "drinks": {
        "en": ["water", "sparkling water", "juice", "orange juice", "soda", "cola", "beer", "wine", "energy drink",
               "iced tea", "lemonade", "mineral water"],
        "tr": ["su", "maden suyu", "soda", "meyve suyu", "portakal suyu", "kola", "gazoz", "bira", "şarap",
               "enerji içeceği", "soğuk çay", "limonata", "şalgam"],
    },
    "household": {
        "en": ["detergent", "dish soap", "dishwasher tablets", "laundry detergent", "paper towels", "toilet paper",
               "trash bags", "sponges", "bleach", "cleaner", "aluminum foil", "cling film", "light bulbs", "batteries",
               "fabric softener", "napkins"],
        "tr": ["deterjan", "bulaşık deterjanı", "bulaşık makinesi tableti", "çamaşır deterjanı", "kağıt havlu",
               "tuvalet kağıdı", "çöp torbası", "sünger", "çamaşır suyu", "yüzey temizleyici", "alüminyum folyo",
               "streç film", "ampul", "pil", "yumuşatıcı", "peçete"],
    },
    "personalCare": {
        "en": ["shampoo", "conditioner", "toothpaste", "toothbrush", "deodorant", "razor", "shaving cream",
               "body wash", "soap", "lotion", "sunscreen", "cotton pads", "tissues", "dental floss", "hand cream"],
        "tr": ["şampuan", "saç kremi", "diş macunu", "diş fırçası", "deodorant", "jilet", "tıraş köpüğü", "duş jeli",
               "sabun", "losyon", "güneş kremi", "pamuk", "mendil", "diş ipi", "el kremi", "ped"],
    },
    "other": {
        "en": ["birthday card", "gift wrap", "flowers", "pet food", "cat litter", "notebook", "pens", "candles",
               "phone charger", "umbrella"],
        "tr": ["doğum günü kartı", "hediye paketi", "çiçek", "kedi maması", "kedi kumu", "defter", "kalem", "mum",
               "şarj kablosu", "şemsiye"],
    },
}
