// GENERATED by tool/l10n_strings.py — do not edit.
// ignore_for_file: annotate_overrides, type=lint
import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

import '../core/l10n/assistant_name.dart';
import 'gen/app_localizations.dart';
import 'gen/app_localizations_en.dart';
import 'gen/app_localizations_tr.dart';

class _NamedEn extends AppLocalizationsEn {
  _NamedEn(this.assistant);
  final String assistant;
  String _r(String s) => renameAssistant(s, assistant, turkish: false);
  @override
  String get planDayEmpty => _r(super.planDayEmpty);
  @override
  String get planWithLio => _r(super.planWithLio);
  @override
  String get quizRight => _r(super.quizRight);
  @override
  String get gardenTitle => _r(super.gardenTitle);
  @override
  String gardenCharging(int count) => _r(super.gardenCharging(count));
  @override
  String gardenExploring(String time) => _r(super.gardenExploring(time));
  @override
  String get gardenGift => _r(super.gardenGift);
  @override
  String get notifGardenTitle => _r(super.notifGardenTitle);
  @override
  String get lioHelpHide => _r(super.lioHelpHide);
  @override
  String get foodWeekIntro => _r(super.foodWeekIntro);
  @override
  String get premiumFeaturePostcards => _r(super.premiumFeaturePostcards);
  @override
  String get notifPlanBody => _r(super.notifPlanBody);
  @override
  String get streakSaveBody => _r(super.streakSaveBody);
  @override
  String get streakSaveBodyPremium => _r(super.streakSaveBodyPremium);
  @override
  String get lioLearnsSetting => _r(super.lioLearnsSetting);
  @override
  String get lioLearnsHelp => _r(super.lioLearnsHelp);
  @override
  String get mascotAsk => _r(super.mascotAsk);
  @override
  String get lioName => _r(super.lioName);
  @override
  String get lioAsk => _r(super.lioAsk);
  @override
  String get lioHide => _r(super.lioHide);
  @override
  String get lioHidden => _r(super.lioHidden);
  @override
  String get lioSetting => _r(super.lioSetting);
  @override
  String get lioSettingHelp => _r(super.lioSettingHelp);
  @override
  String brainGreeting(String name) => _r(super.brainGreeting(name));
  @override
  String get brainGreetingNoName => _r(super.brainGreetingNoName);
  @override
  String get brainAnswerLabel => _r(super.brainAnswerLabel);
  @override
  String get askLioAbout => _r(super.askLioAbout);
  @override
  String get recipeNoMatch => _r(super.recipeNoMatch);
  @override
  String get lioSuggestions => _r(super.lioSuggestions);
  @override
  String get actTalk => _r(super.actTalk);
  @override
  String get journalKnowsTitle => _r(super.journalKnowsTitle);
}

class _NamedTr extends AppLocalizationsTr {
  _NamedTr(this.assistant);
  final String assistant;
  String _r(String s) => renameAssistant(s, assistant, turkish: true);
  @override
  String get planDayEmpty => _r(super.planDayEmpty);
  @override
  String get planWithLio => _r(super.planWithLio);
  @override
  String get quizRight => _r(super.quizRight);
  @override
  String get gardenTitle => _r(super.gardenTitle);
  @override
  String gardenCharging(int count) => _r(super.gardenCharging(count));
  @override
  String gardenExploring(String time) => _r(super.gardenExploring(time));
  @override
  String get gardenGift => _r(super.gardenGift);
  @override
  String get notifGardenTitle => _r(super.notifGardenTitle);
  @override
  String get lioHelpHide => _r(super.lioHelpHide);
  @override
  String get foodWeekIntro => _r(super.foodWeekIntro);
  @override
  String get premiumFeaturePostcards => _r(super.premiumFeaturePostcards);
  @override
  String get notifPlanBody => _r(super.notifPlanBody);
  @override
  String get streakSaveBody => _r(super.streakSaveBody);
  @override
  String get streakSaveBodyPremium => _r(super.streakSaveBodyPremium);
  @override
  String get lioLearnsSetting => _r(super.lioLearnsSetting);
  @override
  String get lioLearnsHelp => _r(super.lioLearnsHelp);
  @override
  String get mascotAsk => _r(super.mascotAsk);
  @override
  String get lioName => _r(super.lioName);
  @override
  String get lioAsk => _r(super.lioAsk);
  @override
  String get lioHide => _r(super.lioHide);
  @override
  String get lioHidden => _r(super.lioHidden);
  @override
  String get lioSetting => _r(super.lioSetting);
  @override
  String get lioSettingHelp => _r(super.lioSettingHelp);
  @override
  String brainGreeting(String name) => _r(super.brainGreeting(name));
  @override
  String get brainGreetingNoName => _r(super.brainGreetingNoName);
  @override
  String get brainAnswerLabel => _r(super.brainAnswerLabel);
  @override
  String get askLioAbout => _r(super.askLioAbout);
  @override
  String get recipeNoMatch => _r(super.recipeNoMatch);
  @override
  String get lioSuggestions => _r(super.lioSuggestions);
  @override
  String get actTalk => _r(super.actTalk);
  @override
  String get journalKnowsTitle => _r(super.journalKnowsTitle);
}

/// App strings with the user's name for the assistant instead of "Lio".
class NamedLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const NamedLocalizationsDelegate(this.assistant);
  final String assistant;

  @override
  bool isSupported(Locale locale) => AppLocalizations.delegate.isSupported(locale);

  @override
  Future<AppLocalizations> load(Locale locale) {
    final base = lookupAppLocalizations(locale);
    if (assistant.trim().isEmpty || assistant == 'Lio') return SynchronousFuture(base);
    return SynchronousFuture(base.localeName.startsWith('tr') ? _NamedTr(assistant) : _NamedEn(assistant));
  }

  @override
  bool shouldReload(NamedLocalizationsDelegate old) => old.assistant != assistant;
}
